# .pre-commit-config.yaml

# mypi
repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910-1'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args:
          - "--ignore-missing-imports"

#-   repo: https://github.com/pre-commit/mirrors-yapf
#    rev: 'v0.31.0'  # Use the sha / tag you want to point at
#    hooks:
#    -   id: yapf

# flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
      args: # arguments to configure flake8
        # making isort line length compatible with black
        - "--max-line-length=127"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"

        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E266,E501,E402"

# black
- repo: https://github.com/ambv/black
  rev: 22.8.0
  hooks:
  - id: black
    args:
      - --line-length=127

# isort
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "--filter-files"]
